openapi: 3.0.4
info:
  title: SEQTA Learn API
  description: |-
    # Warning: abuse of these services may result in suspension for your school and legal action could be taken
    Reference for the SEQTA learn API, provided by the BetterSEQTA+ Team
    # The BetterSEQTA+ team advises that you do not share any cookies used for these activites - the JSESSIONID can be used to do actions on your behalf without you knowing - treat them as passwords.
  termsOfService: https://sockycat.net/404
  contact:
    email: betterseqta.plus@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.27-SNAPSHOT
servers:
- url: https://your.url/seqta/student
security:
- cookie: []
- ga: []
tags:
- name: General
  description: General APIs such as logging in and finding settings.
  externalDocs:
    description: Find out more
    url: https://swagger.io
- name: Direct Messages
  description: Sending and receiving messages
- name: Assessments
  description: Assessment-related api calls
- name: Courses
  description: Courses-related API calls.
- name: Misc
  description: Things like the kitty on the 404 page and the mp3s for notifications
paths:
  /login:
    post:
      tags:
      - General
      summary: Get login information from SEQTA. REQUIRES THE _ga COOKIE.
      description: "Returns name, some info about the user and (if applicable) SAML\
        \ information"
      operationId: updatePet
      requestBody:
        content:
          application/json:
            schema:
              example:
                mode: normal
                redirect_url: any string
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example:
                schema:
                  payload:
                    lastAccessedTime: Number
                    personUUID: String
                    meta:
                      code: Number
                      governmentID: Any
                    clientIP: user identification
                    saml:
                    - autologin: Boolean
                      request: the output of ms auth
                      relaystate: the output of ms auth
                      method: POST
                      signature: secret b64 key
                      slo: Boolean
                      label: String
                      sigalg: String
                      url: the query for ms auth
                    userDesc: String
                    id: Number
                    type: student
                    userName: String
                    userCode: String
                    email: String
                    status: "200"
                  status: "200"
      x-swagger-router-controller: General
  /photo/get:
    get:
      tags:
      - General
      summary: Get student
      description: Returns an array of settings
      operationId: get_photo_of_student
      parameters:
      - name: uuid
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          description: UUID of the user
      - name: format
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          description: The resolution of the file
          enum:
          - low
          - med
          - high
      responses:
        "200":
          description: The user's image
          content:
            image/jpeg:
              schema:
                example:
                - "To protect the safety of people, no image was provided. It would\
                  \ return an image."
                x-content-type: image/jpeg
      x-swagger-router-controller: General
  /heartbeat:
    post:
      tags:
      - General
      summary: Keep-alive the session
      description: Returns the current data for the user
      operationId: heartbeat
      requestBody:
        content:
          application/json:
            schema:
              example:
                timestamp: 2025-05-18 10:11:37.0
                hash: "#?page=/messages"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example:
                payload:
                  identifier: any
                  version: 2025.4.1-master-20250409-184
                  uuid: your user uuid
                  notifications: []
                  ts: 2025-05-18 10:16:37.08500
                status: "200"
      x-swagger-router-controller: General
  /file/upload/xhr2:
    post:
      tags:
      - General
      summary: Upload a file using xhr2
      description: The only way to upload a file
      operationId: fileUploadXhr2POST
      requestBody:
        content:
          manymimetypes:
            schema:
              example: "As it is a XHR2 upload, the data can't be shared here due\
                \ to the nature of one."
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example:
                payload:
                  filename: literally anything.js
                  context_uuid: 998955d6-60c6-44d2-98f6-13f086d8aa1e
                  mimetype: text/html
                  id: "674132"
                  created_date: 2025-05-18T11:03:16.947
                  uuid: in most cases the same as the context_uuid
                  created_by: 1131
                status: "200"
      x-swagger-router-controller: General
  /settings:
    post:
      tags:
      - General
      summary: Get settings
      description: Returns an array of settings
      operationId: settings
      parameters:
      - name: any
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          description: This can be anything. Just pass a space as it is required
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example:
                payload:
                  global.communications.phone.exit_code:
                    value: String
                  global.notifications.email.minimumAge:
                    value: String
                  global.ai.api.baseurl:
                    value: https://ai.seqta.com/
                  coneqt-s.events.contacts.enabled:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.events:
                    value: enabled/disabled
                  coneqt-s.messages.students.enabled:
                    value: enabled/disabled
                  coneqt-s.events.staff.enabled:
                    value: enabled/disabled
                  global.datacube:
                    value: enabled/disabled
                  global.folios:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.selfassessment:
                    value: enabled/disabled
                  coneqt-s.forum.photos:
                    value: enabled/disabled
                  global.ai.lessonplan:
                    value: enabled/disabled
                  coneqt-s.page.forums:
                    value: enabled/disabled
                  global.myed:
                    value: enabled/disabled
                  coneqt-s.page.folios:
                    value: enabled/disabled
                  coneqt-s.events.students.enabled:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.applications:
                    value: enabled/disabled
                  coneqt-s.events.tutors.enabled:
                    value: enabled/disabled
                  coneqt-s.page.reports:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.timetable:
                    value: enabled/disabled
                  coneqt-s.mediaRecorder.enabled:
                    value: enabled/disabled
                  coneqt-s.page.goals:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.electives:
                    value: enabled/disabled
                  coneqt-s.timetable.email:
                    value: enabled/disabled
                  global.microsoftTeams.pilot:
                    value: enabled/disabled
                  coneqt-s.filesize.limit:
                    value: String
                  coneqt-s.synergetic.community.pages.docs:
                    value: enabled/disabled
                  global.ai.credits:
                    value: String
                  coneqt-s.googleAnalytics: {}
                  url.coneqt-s:
                    value: String
                  global.dashlet.summarised-assessment-feedback:
                    value: enabled/disabled
                  global.microsoftTeams.directoryId:
                    value: String
                  global.forums.usePrefName:
                    value: enabled/disabled
                  coneqt-s.page.notices:
                    value: enabled/disabled
                  attendance.defaults.time_from:
                    value: String
                  coneqt-s.synergetic.community.pages.accommodation:
                    value: enabled/disabled
                  global.ai.client.secret:
                    value: String
                  global.url.seqtaresources:
                    value: String
                  coneqt-s.assessments.customtext:
                    value: enabled/disabled
                  global.ai.api.token:
                    value: token
                  coneqt-s.forum.greeting:
                    value: String
                  global.requestedAbsences:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.absences:
                    value: enabled/disabled
                  global.datacube.dailyexport:
                    value: enabled/disabled
                  global.microsoftTeams.domainName:
                    value: String
                  coneqt-s.timetable.attendance:
                    value: enabled/disabled
                  attendance.defaults.time_to:
                    value: String
                  coneqt-s.messages.contacts.enabled:
                    value: enabled/disabled
                  global.microsoftTeams.applicationId:
                    value: String
                  coneqt-s.goals.message:
                    value: String
                  global.email.defaultFrom:
                    value: String
                  global.microsoftTeams.clientSecret:
                    value: String
                  coneqt-s.page.documents:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.results:
                    value: enabled/disabled
                  coneqt-s.synergetic.community.pages.excursions:
                    value: enabled/disabled
                  global.microsoftTeams.features:
                    value: enabled/disabled
                  global.email.feedbackExtra:
                    value: String
                  coneqt-s.courses:
                    value: enabled/disabled
                  global.oneDrive.clientId:
                    value: String
                status: "200"
      x-swagger-router-controller: General
  /load/message#1:
    post:
      tags:
      - Direct Messages
      summary: Get labels
      description: Returns the labels
      operationId: load_messages_1
      requestBody:
        content:
          application/json:
            schema:
              example:
                action: labels
      responses:
        "200":
          description: Outcome of iterables is dependent on what your school has.
            This is the most common arrangement
          content:
            application/json:
              example:
                payload:
                - unread: 0
                  label: inbox
                - unread: 0
                  label: outbox
                - unread: 0
                  label: trash
                - unread: 0
                  label: starred
                status: "200"
      x-swagger-router-controller: DirectMessages
  /load/message#2:
    post:
      tags:
      - Direct Messages
      summary: Get messages in an inbox
      description: Retrive the messages in an import
      operationId: load_messages_2
      requestBody:
        content:
          application/json:
            schema:
              example:
                searchValue: ""
                sortBy: date
                sortOrder: desc
                action: list
                label: inbox
                offset: 0
                limit: 100
      responses:
        "200":
          description: NOTE&colon; Expect more than one iterable. It is defined by
            the `limit` parameter in the request.
          content:
            application/json:
              example:
                payload:
                  hasMore: true
                  messages:
                  - date: 2025-05-16 11:05:30.500763+09:30
                    attachments: false
                    read: 1
                    sender: Mr. Smith
                    subject: Exam practice sheets
                    sender_type: staff
                    attachmentCount: 0
                    id: 69420
                    sender_id: 940
                    participants:
                    - name: John Sample
                      photo: 14566782-b600-40cf-a76d-537b198578e9
                      type: student
                  ts: 2025-05-18 10:14:39.71900
                status: "200"
      x-swagger-router-controller: DirectMessages
  /load/message#3:
    post:
      tags:
      - Direct Messages
      summary: Get a message from the inbox
      description: Load a message from the inbox
      operationId: load_messages_3
      requestBody:
        content:
          application/json:
            schema:
              example:
                action: message
                id: 69420
      responses:
        "200":
          description: The response
          content:
            application/json:
              example:
                payload:
                  date: 2025-05-16 10:22:05.648225+09:30
                  blind: false
                  read: true
                  subject: file
                  sender_type: student
                  contactMeta: []
                  sender_id: 1679
                  sender_photo: 8c82e311-9701-47fa-9c87-16b551ea1144
                  studentMeta: []
                  starred: false
                  contents: ""
                  sender: Some One
                  files:
                  - filename: file.json
                    size: "1"
                    context_uuid: uuid
                    mimetype: application/json
                    id: 599042
                    created_date: 2025-05-16 10:22:03.599289+09:30
                    uuid: same as context_uuid most of the time
                    created_by: "69"
                  id: 635100
                  participants:
                  - read: 1
                    name: Sammy Smith
                    photo: 14566782-b600-40cf-a76d-537b198578e9
                    id: 70
                    type: student
                status: "200"
      x-swagger-router-controller: DirectMessages
  /save/message:
    post:
      tags:
      - Direct Messages
      summary: Send a message to a user
      description: Sends a message to someone. Returns a status code and some info.
      operationId: send_message
      requestBody:
        content:
          application/json:
            schema:
              example:
                subject: e
                contents: e
                participants:
                - staff: true
                  id: 589
                blind: false
                files:
                - same as the loading message one
      responses:
        "200":
          description: "The response. The `id` property is the message id, not the\
            \ receipent's id."
          content:
            application/json:
              example:
                payload:
                  subject: e
                  recipients: 1
                  id: 635615
                status: "200"
      x-swagger-router-controller: DirectMessages
  /js/images/kitten.png:
    get:
      tags:
      - Misc
      summary: get the cute cate image
      description: cat
      operationId: cat
      responses:
        "200":
          description: cat. literally just cat
          content:
            image/jpeg:
              example: You can find out :)
      servers:
      - url: https://your.url
      x-swagger-router-controller: Misc
  /js/audio/notify.mp3:
    get:
      tags:
      - Misc
      summary: notify sound
      description: the notify sound
      operationId: notify_sound
      responses:
        "206":
          description: sound
          content:
            audio/mp3:
              example: You can find out :)
      servers:
      - url: https://your.url
      x-swagger-router-controller: Misc
  /js/audio/question.mp3:
    get:
      tags:
      - Misc
      summary: question sound
      description: the sound that plays when you compose a message on loud settings
      operationId: question_sound
      responses:
        "206":
          description: sound
          content:
            audio/mp3:
              example: You can find out :)
      servers:
      - url: https://your.url
      x-swagger-router-controller: Misc
components:
  schemas: {}
  securitySchemes:
    cookie:
      type: apiKey
      name: JSESSIONID
      in: cookie
    ga:
      type: apiKey
      name: _ga
      in: cookie
